# compose.yaml
services:
  site:
    image: hugomods/hugo:latest
    container_name: my-portfolio
    # Maps current folder to /src inside container
    volumes:
      - .:/src
    # Maps port 1313
    ports:
      - "1313:1313"
    # The command to run (server mode with draft binding)
    command: server --bind 0.0.0.0 --buildDrafts