baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Koshala's Portfolio"  
theme = "shibui"

# This enables raw HTML in your posts (useful for embedding YouTube/demos)
[markup.goldmark.renderer]
unsafe = true


[params]
  [params.author]
    name = "Koshala Chathuranga"
  description = "A dev log of my leisure projects"
  # Social links (These usually appear in the footer or sidebar)
  github = "YourGitHubUsername"
  linkedin = "YourLinkedInUsername"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"   
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3